# Generated by Django 4.2.6 on 2023-12-19 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 6, 58, 30, 113099, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 6, 58, 30, 113099, tzinfo=datetime.timezone.utc)),
        ),
    ]
